# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b332010b68e38b6b1bb072bd867961b9fb1278a80d68d56ffd5ea9991c53af1ab5a9a662cca7e12d72ed0c90de4d81d94bd28a1baab6dc146f1386b238c9419

test:
  secret_key_base: facb63a99332b5ef451bfdbc4e5d58137890be10e3a5f1ca1ece8c5efebf7833d1e1ed82c4c0f3a3e55d2a38f8e3f1f207a7bcd3c4757127710308230718eefc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
